name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    name: cd
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: レジストリログイン
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: コンテナイメージビルド
        run: docker image build -t ghcr.io/${{ github.repository }}:latest .
      - name: レジストリへ登録
        run: docker image push ghcr.io/${{ github.repository }}:latest
